### ISSUE TITLE
Improvement ideas

### ISSUE THREAD

**Issue by medinae** [acjzz/gokaf#22]
First of all, **thanks** for writing that package.
I can already think about usage at work and would like to contribute to it.

I took time to read carefully the code, and i find it really clear, well written.
I still have few suggestions :

- What about using **Fuzz** testing (https://github.com/google/gofuzz) ? I really believe it can make a lot of sense, more precisely inside the `Topic` related tests. Trying to test the handling workflow with a crazy amount of possible values can be really valuable, and can help us cover a lot of usability scenarios.

- https://github.com/acjzz/gokaf/blob/8a7e54a79169eba890984268057ea9fa4eb804bd/topic.go#L21

Here, i feel the usage of variadic parameters coupled to the fact that the topic will only take the first argument if any exists can confuse the user at some point.
Of course, usage of variadic is  really smart and cover the fact that golang does not offer optional argument capabilities, but my idea is to be more strict, and return an explicit error if more than one `numConsumer` is passed as argument.

- I would also try to use as much early returns as i can, and avoiding `else`'s as much as possible to make the code easier to ready and reduce cyclomatic complexity.

Examples :
https://github.com/acjzz/gokaf/blob/8a7e54a79169eba890984268057ea9fa4eb804bd/consumer.go#L29

https://github.com/acjzz/gokaf/blob/8a7e54a79169eba890984268057ea9fa4eb804bd/engine.go#L55

For that last example, i would for instance find that smoother on eyes : 
```
func (ge *Engine) AddTopic(name string, handler func(string, interface{}), numConsumers ...int) {
	name = strings.ToLower(name)
        if _, ok := ge.topics[name]; ok {   
              ge.logger.Warn("topic already exists")
              return
        }

        if len(numConsumers) > 0 {
                ge.topics[name] = NewTopic(ge.ctx, name, handler, numConsumers[0])
        } else {
                ge.topics[name] = NewTopic(ge.ctx, name, handler)
        }
        ge.topics[name].run()
}
```
Le me know what do you think.
Of course all of that are just details, but i just wanted to give my thoughts on that.

Another time, thanks for your awesome work.
I look forward to contribute, please create Issue when you have any feature idea, so as we can contribute.

Cheers !

**Comment by acjzz** [comment]
Hi @medinae, 

First of all thanks for your feedback and I really appreciate your thoughts. My apologies as well to did not find the time til now to go through your comments.

Please see my feedback below:
- Regarding usage of Fuzz is necessary for testing and validate the proper usage.
- Regarding of the usage of variadic parameters it is a quick solution to handle multiple consumers per topic. And needs to be improved or redesign.
- Regarding use as much early returns as i can, and avoiding else's as much as possible to make the code easier I am align and I really appreciate 

Currently I am working on some use case using gokaf to really be able to measure the code as well as I plan to create some benchmarking for gokaf to be able to evaluate the changes from the performance point of view.

Another time, thanks for your time and comments about gokaf, I really appreciated.

And regarding new features I prefer first to validate the assumption of its usage in a real scenario. And build a strong test suite around it

Cheers!
