### ISSUE TITLE
New feature : Multi-handler topics.

### ISSUE THREAD

**Issue by medinae** [acjzz/gokaf#23]
Hello,
I'm thinking about implementing a kind of topic broadcaster feature.

The idea is adding a new type of `topic` (so will need to add a related interface), that will act as a topic container and will contain multiple classic (existing) topics. It can actually be compared to the exchange features that most of the message brokers systems has. 
The final result would be a user publishing go that kind of topic, will see his stream message be processed by multiple handlers.

The usage would be something like :

```go
func main() {
	ge := gokaf.NewEngine("MyEngine", logrus.DebugLevel)

        aragorn := NewTopic(ge.ctx, "aragorn", func(topic string, obj interface{}) {
            fmt.Printf("Consumed '%v' from topic aragorn", obj, topic)
        })
        legolas := NewTopic(ge.ctx, "legolas", func(topic string, obj interface{}) {
            fmt.Printf("Consumed '%v' from topic legolas", obj)
        })
       
	ge.AddTopicContainer("soldiers", aragorn, legolas)

	e := ge.Publish("soldiers", fmt.Sprintf("Message%d", i))
	if e != nil {
		fmt.Printf("publishing to topic 'soldiers', err: %v", e)
	}

	ge.Stop()
}
```

Of course the naming is weird here, but that's just a simple boilerplate code to express my idea.

**Comment by acjzz** [comment]
Hi @medinae,

Yes your right, in fact message topic streaming is something I had in mind when I implemented gokaf. In fact gokaf was done to emulate nowadays stream capacities with minimal need of resources.

I would like to keep gokaf simple and efficient.

Anyway streaming capability is something that I had in mind to implement it as another project that relies on gokaf. 

In fact before that gokaf requires a proper module versioning implementation and a simple CI/CD ;) 

Thanks again for your time and comments 👍
